version: "3.8"

services:

  backend:
    image: 'case-study-backend'
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    build:
      context: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
